export default function HistoryPage() {
    const versions = [
      { id: 1, date: '2024-05-20', author: 'AI', changes: 3 },
      { id: 2, date: '2024-05-18', author: 'User', changes: 5 },
      { id: 3, date: '2024-05-15', author: 'AI', changes: 2 }
    ]
  
    return (
      <div className="max-w-3xl mx-auto bg-white p-6 rounded-lg shadow">
        <h1 className="text-2xl font-bold text-[#012169] mb-6">Version History</h1>
        
        <div className="space-y-4">
          {versions.map(version => (
            <div key={version.id} className="border rounded-lg p-4 hover:bg-gray-50">
              <div className="flex justify-between">
                <div>
                  <span className="font-medium">Version {version.id}</span>
                  <span className="text-gray-500 ml-2">({version.date})</span>
                </div>
                <span className="bg-blue-100 text-blue-800 px-2 py-1 rounded-full text-xs">
                  {version.changes} changes
                </span>
              </div>
              <div className="mt-2 text-sm text-gray-600">
                Generated by: {version.author}
              </div>
              <button className="mt-2 text-sm text-[#012169] hover:underline">
                View Changes
              </button>
            </div>
          ))}
        </div>
  
        {/* Mock diff viewer (would use a library like react-diff-viewer in real app) */}
        <div className="mt-8 border-t pt-6">
          <h2 className="font-semibold mb-4">Comparing Version 2 → 3</h2>
          <div className="grid grid-cols-2 gap-4">
            <div className="border rounded-lg p-4">
              <h3 className="font-medium text-red-600">Removed</h3>
              <ul className="mt-2 space-y-2 text-sm">
                <li className="line-through">"Store last 4 digits of credit cards"</li>
              </ul>
            </div>
            <div className="border rounded-lg p-4">
              <h3 className="font-medium text-green-600">Added</h3>
              <ul className="mt-2 space-y-2 text-sm">
                <li>"Tokenize all payment data"</li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    )
  }